import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import initSqlJs, { type Database, type SqlValue } from 'sql.js';
import type { Goal, ProjectMetadata, Task } from '@forge/ipc';

type Row = Record<string, unknown>;
const id = () => crypto.randomUUID();

export class StorageService {
  private db: Database | null = null;
  private filePath: string | null = null;
  private rootPath: string | null = null;
  async init(rootPath: string): Promise<void> { const directory = path.join(rootPath, '.forge'); await fs.mkdir(directory, { recursive: true }); this.filePath = path.join(directory, 'metadata.sqlite'); this.rootPath = rootPath; const SQL = await initSqlJs(); const bytes = await fs.readFile(this.filePath).catch(() => null); this.db = bytes ? new SQL.Database(bytes) : new SQL.Database(); this.db.run('PRAGMA foreign_keys = ON'); this.db.run(`CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT NOT NULL, root_path TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS goals (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT, status TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id)); CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT, status TEXT NOT NULL, priority TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id));`); await this.ensureProject(); }
  async close(): Promise<void> { await this.persist(); this.db?.close(); this.db = null; this.filePath = null; this.rootPath = null; }
  async dashboard(): Promise<ProjectMetadata | null> { const project = this.one('SELECT * FROM projects WHERE root_path = ?', [this.rootPath]); if (!project) return null; return { id: String(project.id), name: String(project.name), rootPath: String(project.root_path), createdAt: Number(project.created_at), updatedAt: Number(project.updated_at), goals: this.goals(String(project.id)), tasks: this.tasks(String(project.id)) }; }
  async createGoal(title: string, description?: string): Promise<Goal> { if (!title.trim()) throw new Error('Goal title is required.'); const project = await this.dashboard(); if (!project) throw new Error('No project metadata exists.'); const now = Date.now(); const goal: Goal = { id: id(), title: title.trim(), description, status: 'active', createdAt: now, updatedAt: now }; this.ready().run('INSERT INTO goals VALUES (?, ?, ?, ?, ?, ?, ?)', [goal.id, project.id, goal.title, description ?? null, goal.status, now, now]); await this.persist(); return goal; }
  async createTask(title: string, description?: string, priority: Task['priority'] = 'medium'): Promise<Task> { if (!title.trim()) throw new Error('Task title is required.'); const project = await this.dashboard(); if (!project) throw new Error('No project metadata exists.'); const now = Date.now(); const task: Task = { id: id(), title: title.trim(), description, status: 'todo', priority, createdAt: now, updatedAt: now }; this.ready().run('INSERT INTO tasks VALUES (?, ?, ?, ?, ?, ?, ?, ?)', [task.id, project.id, task.title, description ?? null, task.status, priority, now, now]); await this.persist(); return task; }
  private async ensureProject(): Promise<void> { if (!this.rootPath) throw new Error('Storage is not initialized.'); if (this.one('SELECT id FROM projects WHERE root_path = ?', [this.rootPath])) return; const now = Date.now(); this.ready().run('INSERT INTO projects VALUES (?, ?, ?, ?, ?)', [id(), path.basename(this.rootPath), this.rootPath, now, now]); await this.persist(); }
  private goals(projectId: string): Goal[] { return this.all('SELECT * FROM goals WHERE project_id = ? ORDER BY created_at DESC', [projectId]).map((row) => ({ id: String(row.id), title: String(row.title), description: row.description ? String(row.description) : undefined, status: String(row.status) as Goal['status'], createdAt: Number(row.created_at), updatedAt: Number(row.updated_at) })); }
  private tasks(projectId: string): Task[] { return this.all('SELECT * FROM tasks WHERE project_id = ? ORDER BY created_at DESC', [projectId]).map((row) => ({ id: String(row.id), title: String(row.title), description: row.description ? String(row.description) : undefined, status: String(row.status) as Task['status'], priority: String(row.priority) as Task['priority'], createdAt: Number(row.created_at), updatedAt: Number(row.updated_at) })); }
  private all(sql: string, params: SqlValue[] = []): Row[] { const result = this.ready().exec(sql, params); if (!result[0]) return []; return result[0].values.map((values) => Object.fromEntries(result[0].columns.map((column, index) => [column, values[index]]))); }
  private one(sql: string, params: SqlValue[] = []): Row | undefined { return this.all(sql, params)[0]; }
  private ready(): Database { if (!this.db) throw new Error('Storage is not initialized.'); return this.db; }
  private async persist(): Promise<void> { if (this.db && this.filePath) await fs.writeFile(this.filePath, this.db.export()); }
}
