import { useCallback, useEffect, useMemo, useState, type JSX } from 'react';
import Editor from '@monaco-editor/react';
import { marked } from 'marked';
import type { DashboardData, FileNode, GitDiff, GitStatus, WorkspaceInfo } from '@forge/ipc';
import ChatPanel from './components/ChatPanel';

const languageFor = (extension?: string) => ({ md: 'markdown', ts: 'typescript', tsx: 'typescript', js: 'javascript', jsx: 'javascript', json: 'json', py: 'python', cpp: 'cpp', c: 'c', css: 'css', html: 'html' }[extension ?? ''] ?? 'plaintext');
const call = async <T,>(promise: Promise<{ success: boolean; data?: T; error?: { message: string } }>): Promise<T> => { const result = await promise; if (!result.success) throw new Error(result.error?.message ?? 'Request failed.'); return result.data as T; };

export default function App(): JSX.Element {
  const [workspace, setWorkspace] = useState<WorkspaceInfo | null>(null); const [files, setFiles] = useState<FileNode[]>([]); const [active, setActive] = useState<FileNode | null>(null); const [content, setContent] = useState(''); const [savedContent, setSavedContent] = useState(''); const [status, setStatus] = useState<GitStatus | null>(null); const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [diff, setDiff] = useState<GitDiff | null>(null); const [commitMessage, setCommitMessage] = useState(''); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState(false);
  const refresh = useCallback(async () => { if (!workspace) return; try { const [nextFiles, nextStatus, nextDashboard] = await Promise.all([call<FileNode[]>(window.forge.invoke('file.list', {})), call<GitStatus>(window.forge.invoke('git.status', undefined)).catch(() => null), call<DashboardData>(window.forge.invoke('meta.dashboard', undefined))]); setFiles(nextFiles); setStatus(nextStatus); setDashboard(nextDashboard); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not refresh workspace.'); } }, [workspace]);
  useEffect(() => { refresh(); }, [refresh]);
  const openWorkspace = async () => { try { const opened = await call<WorkspaceInfo>(window.forge.invoke('workspace.open', undefined)); setWorkspace(opened); setActive(null); setContent(''); setError(null); } catch (cause) { if ((cause as Error).message !== 'Workspace selection was cancelled.') setError((cause as Error).message); } };
  const openFile = async (node: FileNode) => { if (node.type === 'directory') return; try { const file = await call<{ content: string }>(window.forge.invoke('file.read', { path: node.relativePath })); setActive(node); setContent(file.content); setSavedContent(file.content); setPreview(node.extension === 'md'); } catch (cause) { setError((cause as Error).message); } };
  const save = async () => { if (!active) return; try { await call(window.forge.invoke('file.write', { path: active.relativePath, content })); setSavedContent(content); refresh(); } catch (cause) { setError((cause as Error).message); } };
  const createFile = async () => { const fileName = window.prompt('New relative file path (for example notes/idea.md):'); if (!fileName) return; try { await call(window.forge.invoke('file.create', { path: fileName, type: 'file', content: '' })); await refresh(); } catch (cause) { setError((cause as Error).message); } };
  const deleteActive = async () => { if (!active || !window.confirm(`Delete ${active.relativePath}? This cannot be undone.`)) return; try { await call(window.forge.invoke('file.delete', { path: active.relativePath })); setActive(null); setContent(''); await refresh(); } catch (cause) { setError((cause as Error).message); } };
  const createGoal = async () => { const title = window.prompt('Goal title:'); if (!title) return; try { await call(window.forge.invoke('meta.goal.create', { title })); refresh(); } catch (cause) { setError((cause as Error).message); } };
  const createTask = async () => { const title = window.prompt('Task title:'); if (!title) return; try { await call(window.forge.invoke('meta.task.create', { title })); refresh(); } catch (cause) { setError((cause as Error).message); } };
  const commit = async () => { try { await call(window.forge.invoke('git.commit', { message: commitMessage })); setCommitMessage(''); refresh(); } catch (cause) { setError((cause as Error).message); } };
  const stage = async (file: string) => { try { await call(window.forge.invoke('git.stage', { files: [file] })); setDiff(await call(window.forge.invoke('git.diff', { staged: false }))); refresh(); } catch (cause) { setError((cause as Error).message); } };
  const renderMarkdown = useMemo(() => ({ __html: marked.parse(content) as string }), [content]);
  return <main className="app-shell">
    <header><div className="brand"><span>F</span> FORGE <small>{workspace?.name ?? 'No workspace'}</small></div><div className="toolbar"><button onClick={openWorkspace}>Open workspace</button><button disabled={!workspace} onClick={createFile}>New file</button><button disabled={!active || content === savedContent} onClick={save}>Save</button><button disabled={!active} className="danger" onClick={deleteActive}>Delete</button></div></header>
    {error && <div className="notice"><span>{error}</span><button onClick={() => setError(null)}>×</button></div>}
    {!workspace ? <section className="welcome"><div><p className="eyebrow">LOCAL-FIRST DEVELOPMENT WORKSPACE</p><h1>Think in files.<br />Build with context.</h1><p>Forge keeps your notes, source code, Git history, and project work in one private desktop workspace.</p><button className="primary" onClick={openWorkspace}>Open a project folder</button></div></section> : <section className="workspace-grid">
      <aside className="explorer"><div className="panel-title">EXPLORER <button onClick={refresh}>↻</button></div><FileTree nodes={files} active={active?.relativePath} onOpen={openFile} /></aside>
      <section className="editor-area"><div className="tabbar">{active ? <><span>{active.name}{content !== savedContent ? ' •' : ''}</span><button onClick={() => setPreview(!preview)}>{preview ? 'Edit' : 'Preview'}</button></> : <span>Choose a file to start</span>}</div>{active ? preview && active.extension === 'md' ? <article className="markdown-preview" dangerouslySetInnerHTML={renderMarkdown} /> : <Editor height="100%" theme="vs-dark" language={languageFor(active.extension)} value={content} onChange={(value) => setContent(value ?? '')} options={{ minimap: { enabled: false }, fontSize: 14, padding: { top: 18 } }} /> : <div className="empty-editor">Select a text file from the explorer.<br /><small>Markdown, TypeScript, JavaScript, Python, C++, JSON, CSS, and HTML are supported.</small></div>}</section>
      <aside className="dashboard"><div className="panel-title">PROJECT DASHBOARD</div><div className="health"><strong>{dashboard?.contextHealth.score ?? 0}</strong><span>Context health</span><em>{dashboard?.contextHealth.hasReadme ? 'README found' : 'Add a README'}</em></div><Metric label="Markdown notes" value={dashboard?.contextHealth.noteCount ?? 0} /><Metric label="Code files" value={dashboard?.contextHealth.codeFileCount ?? 0} /><section className="list-section"><div><h3>Goals</h3><button onClick={createGoal}>+</button></div>{dashboard?.project?.goals.length ? dashboard.project.goals.map((goal) => <p key={goal.id}>○ {goal.title}</p>) : <p className="muted">No goals yet.</p>}</section><section className="list-section"><div><h3>Tasks</h3><button onClick={createTask}>+</button></div>{dashboard?.project?.tasks.length ? dashboard.project.tasks.map((task) => <p key={task.id}>□ {task.title}</p>) : <p className="muted">No tasks yet.</p>}</section><section className="list-section"><h3>Recent commits</h3>{dashboard?.recentCommits.length ? dashboard.recentCommits.slice(0, 4).map((commit) => <p key={commit.hash}><code>{commit.shortHash}</code> {commit.message}</p>) : <p className="muted">No commits available.</p>}</section></aside>
      <aside className="dashboard"><ChatPanel /></aside>
      <section className="git-panel"><div className="panel-title">SOURCE CONTROL <span>{status?.branch ?? 'Not a Git repository'}</span><button onClick={() => window.forge.invoke('git.pull', undefined).then(refresh)}>Pull</button><button onClick={() => window.forge.invoke('git.push', undefined).then(refresh)}>Push</button></div><div className="git-content"><div className="changes">{status?.files.length ? status.files.map((file) => <button key={file.path} onClick={() => stage(file.path)}><b>{file.indexStatus}{file.workingStatus}</b>{file.path}</button>) : <p className="muted">Working tree clean.</p>}</div><div className="commit"><input value={commitMessage} onChange={(event) => setCommitMessage(event.target.value)} placeholder="Commit message" /><button disabled={!commitMessage.trim()} onClick={commit}>Commit</button></div><pre className="diff">{diff?.files.flatMap((file) => file.lines.map((line) => `${line.type === 'addition' ? '+' : line.type === 'deletion' ? '-' : ' '} ${line.content}`)).join('\n') || 'Select a changed file to stage and inspect changes.'}</pre></div></section>
    </section>}
  </main>;
}
function Metric({ label, value }: { label: string; value: number }): JSX.Element { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function FileTree({ nodes, active, onOpen }: { nodes: FileNode[]; active?: string; onOpen: (node: FileNode) => void }): JSX.Element { return <ul className="file-tree">{nodes.map((node) => <li key={node.relativePath}><button className={active === node.relativePath ? 'selected' : ''} onClick={() => onOpen(node)}>{node.type === 'directory' ? '⌄ ' : ''}{node.name}</button>{node.children && <FileTree nodes={node.children} active={active} onOpen={onOpen} />}</li>)}</ul>; }
