import { useEffect, useState, type JSX } from 'react';
import type { DesktopApplication, ForgeOsContext, SystemOverview } from '@forge/ipc';
import { forgeInvoke } from '../forge';
const call = async <T,>(promise: Promise<any>): Promise<T> => { const result = await promise; if (!result.success) throw new Error(result.error?.message || 'Request failed.'); return result.data; };
const bytes = (value: number): string => `${(value / 1024 ** 3).toFixed(1)} GB`;
export default function ForgeOsShell(): JSX.Element | null {
  const [context, setContext] = useState<ForgeOsContext | null>(null); const [applications, setApplications] = useState<DesktopApplication[]>([]);
  const [applicationsOpen, setApplicationsOpen] = useState(false); const [systemOpen, setSystemOpen] = useState(false); const [powerOpen, setPowerOpen] = useState(false); const [overview, setOverview] = useState<SystemOverview | null>(null); const [now, setNow] = useState(new Date()); const [error, setError] = useState('');
  useEffect(() => { void call<ForgeOsContext>(forgeInvoke('forge-os.context', undefined)).then(setContext).catch(() => undefined); }, []);
  useEffect(() => { if (!context?.shellMode) return; void call<DesktopApplication[]>(forgeInvoke('forge-os.applications', undefined)).then(setApplications).catch((cause) => setError(String(cause))); const timer = window.setInterval(() => setNow(new Date()), 30_000); return () => window.clearInterval(timer); }, [context?.shellMode]);
  if (!context?.shellMode) return null;
  const action = async (next: 'lock' | 'logout' | 'restart' | 'shutdown'): Promise<void> => { if ((next === 'restart' || next === 'shutdown') && !window.confirm(`${next === 'restart' ? 'Restart' : 'Shut down'} this machine?`)) return; try { await call(forgeInvoke('forge-os.session.action', { action: next })); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  return <><div className="forge-os-bar"><button className="forge-os-apps-button" onClick={() => { setApplicationsOpen(!applicationsOpen); setPowerOpen(false); setSystemOpen(false); }}>Applications</button><button onClick={() => { setSystemOpen(!systemOpen); setApplicationsOpen(false); setPowerOpen(false); if (!overview) void call<SystemOverview>(forgeInvoke('forge-os.overview', undefined)).then(setOverview).catch((cause) => setError(String(cause))); }}>System</button><span className="forge-os-spacer"/><time>{now.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })} · {now.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</time><button onClick={() => { setPowerOpen(!powerOpen); setApplicationsOpen(false); setSystemOpen(false); }}>Session</button></div>
    {error && <div className="forge-os-error">{error}<button onClick={() => setError('')}>×</button></div>}
    {applicationsOpen && <section className="forge-os-popover forge-os-applications"><header><strong>Applications</strong><span>{applications.length} installed</span></header>{applications.map((application) => <button key={application.id} onClick={() => { void call(forgeInvoke('forge-os.application.launch', { id: application.id })).catch((cause) => setError(String(cause))); setApplicationsOpen(false); }}><b>{application.name}</b><small>{application.description || application.categories[0] || 'Application'}</small></button>)}</section>}
    {systemOpen && <section className="forge-os-popover forge-os-system"><header><strong>System Overview</strong></header>{overview ? <dl><dt>Hostname</dt><dd>{overview.hostname}</dd><dt>OS</dt><dd>{overview.os}</dd><dt>Kernel</dt><dd>{overview.kernel}</dd><dt>CPU</dt><dd>{overview.cpu}</dd><dt>Memory</dt><dd>{bytes(overview.memoryBytes)}</dd><dt>Storage free</dt><dd>{bytes(overview.storage.freeBytes)} / {bytes(overview.storage.totalBytes)}</dd><dt>FORGE</dt><dd>{overview.forgeVersion}</dd><dt>FORGE-OS</dt><dd>{overview.forgeOsVersion}</dd><dt>Session</dt><dd>{overview.sessionType}</dd></dl> : <p>Reading system state…</p>}<footer>Network · Audio · Display · Power · Applications · Storage · Appearance · Updates · Security · Recovery · Advanced</footer></section>}
    {powerOpen && <section className="forge-os-popover forge-os-session"><button onClick={() => void action('lock')}>Lock</button><button onClick={() => void action('logout')}>Log out</button><button onClick={() => void action('restart')}>Restart</button><button onClick={() => void action('shutdown')}>Shut down</button><p>Recovery: use Ctrl+Alt+F2 for a console.</p></section>}</>;
}
