import { useCallback, useEffect, useState, type JSX } from 'react';
import type { ActionLogView, ToolRequestView, ToolResultView } from '@forge/ipc';
import { forgeInvoke } from '../forge';

const data = async <T,>(promise: ReturnType<typeof forgeInvoke>): Promise<T> => { const result = await promise; if (!result.success) throw new Error(result.error.message); return result.data as T; };
export default function ToolPanel({ workspaceKey }: { workspaceKey: string }): JSX.Element {
  const [requests, setRequests] = useState<ToolRequestView[]>([]); const [actions, setActions] = useState<ActionLogView[]>([]); const [results, setResults] = useState<Record<string, ToolResultView>>({}); const [error, setError] = useState('');
  const [risk, setRisk] = useState(''); const [outcome, setOutcome] = useState(''); const [tool, setTool] = useState('');
  const [conversationId, setConversationId] = useState(''); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('');
  const refresh = useCallback(async () => { try { const filters: any = {}; if (risk) filters.riskTier = Number(risk); if (outcome) filters.success = outcome === 'success'; if (tool) filters.toolName = tool; if (conversationId) filters.conversationId = conversationId; if (fromDate) filters.from = new Date(`${fromDate}T00:00:00`).getTime(); if (toDate) filters.to = new Date(`${toDate}T23:59:59.999`).getTime(); const [nextRequests, nextActions] = await Promise.all([data<ToolRequestView[]>(forgeInvoke('tool.requests.list', undefined)), data<ActionLogView[]>(forgeInvoke('tool.actions.list', filters))]); setRequests(nextRequests); setActions(nextActions); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }, [risk, outcome, tool, conversationId, fromDate, toDate]);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 2_000); return () => window.clearInterval(timer); }, [workspaceKey, refresh]);
  const approve = async (requestId: string, choice: 'run-once' | 'session'): Promise<void> => { try { const result = await data<ToolResultView>(forgeInvoke('tool.request.approve', { requestId, choice })); setResults((current) => ({ ...current, [requestId]: result })); window.dispatchEvent(new CustomEvent('forge:conversation-updated')); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  return <div className="tool-panel"><div className="tool-filters"><strong>AGENT TOOL REQUESTS & AUDIT</strong><input value={conversationId} onChange={(event) => setConversationId(event.target.value)} placeholder="Conversation ID" /><input value={tool} onChange={(event) => setTool(event.target.value)} placeholder="Tool" /><select value={risk} onChange={(event) => setRisk(event.target.value)}><option value="">All risks</option><option value="0">Tier 0</option><option value="1">Tier 1</option><option value="2">Tier 2</option></select><select value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="">All outcomes</option><option value="success">Success</option><option value="failure">Failure</option></select><input type="date" aria-label="From date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /><input type="date" aria-label="To date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></div>{error && <div className="terminal-error">{error}</div>}
    <div className="tool-columns"><section><h3>Requests</h3>{requests.length ? requests.map((request) => <article className={`tool-request tier-${request.riskTier}`} key={request.id}><header><b>{request.toolName}</b><em>Tier {request.riskTier} · {request.state}</em></header><dl><dt>Reason</dt><dd>{request.reason}</dd><dt>Target</dt><dd>{request.target}</dd><dt>Working directory</dt><dd>{request.workingDirectory ?? 'Active workspace'}</dd><dt>Network</dt><dd>{request.networkAccess ? `Yes · ${request.externalDataDescription ?? 'request metadata only'}` : 'No'}</dd><dt>Expected effect</dt><dd>{request.expectedEffect}</dd></dl>{request.diff && <pre>{request.diff}</pre>}{request.state === 'pending' && <footer><button className="accent" onClick={() => void approve(request.id, 'run-once')}>Run once</button>{request.sessionApprovalAvailable && <button onClick={() => void approve(request.id, 'session')}>Allow exact scope this session</button>}<button onClick={() => void forgeInvoke('tool.request.reject', { requestId: request.id }).then(refresh)}>Reject</button></footer>}{request.state === 'running' && <button onClick={() => void forgeInvoke('tool.request.cancel', { requestId: request.id }).then(refresh)}>Cancel running</button>}{results[request.id] && <pre className="tool-result">{JSON.stringify(results[request.id], null, 2)}</pre>}<button onClick={() => void navigator.clipboard.writeText(JSON.stringify(results[request.id] ?? request, null, 2))}>Copy {results[request.id] ? 'result' : 'request'}</button></article>) : <p className="muted">No agent tool requests in this runtime.</p>}</section>
    <section><h3>Persistent action log</h3>{actions.length ? actions.map((action) => <article className="action-row" key={action.id}><header><b>{action.toolName}</b><em>Tier {action.riskTier} · {action.success ? 'success' : 'failure'}</em></header><p>{action.resultSummary}</p><small>{new Date(action.timestamp).toLocaleString()} · {action.approvalDecision} · {action.executionDurationMs} ms</small><button onClick={() => void navigator.clipboard.writeText(JSON.stringify(action, null, 2))}>Copy</button></article>) : <p className="muted">No matching audited actions.</p>}</section></div>
  </div>;
}
